DELIMITER $$
DROP PROCEDURE IF EXISTS SetInstanceID $$
CREATE PROCEDURE SetInstanceID(IN id CHAR(36))
BEGIN
	DECLARE setID CHAR(36) DEFAULT NULL;
	DECLARE stmt VARCHAR(1024);

	SELECT COLUMN_DEFAULT
	INTO setID
	FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'snappy'
		AND TABLE_NAME = 'ScoreChangeCount'
		AND COLUMN_NAME = 'InstanceID';

	IF setID IS NULL THEN
		SET @SQL := CONCAT('ALTER TABLE ScoreChangeCount MODIFY InstanceID CHAR(36) DEFAULT ''', id, '''');
		PREPARE stmt FROM @SQL;
		EXECUTE stmt;
		DEALLOCATE PREPARE stmt;
	END IF;

	SELECT setID;
END $$
DROP PROCEDURE IF EXISTS UnSetInstanceID $$
CREATE PROCEDURE UnSetInstanceID()
BEGIN
	ALTER TABLE ScoreChangeCount MODIFY InstanceID char(36) NOT NULL;
END $$
DELIMITER ;

CALL SetInstanceID('40081c52-bb10-4f33-9692-527ffe1b540c');

CALL UnSetInstanceID
